// <auto-generated />
using System;
using EducationERP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducationERP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EducationErpDbContext))]
    [Migration("20260404154751_AddExaminationsModule")]
    partial class AddExaminationsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EducationERP.Domain.Entities.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampusId", "Name")
                        .IsUnique();

                    b.ToTable("AcademicYears", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampusId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            EndDate = new DateOnly(2027, 3, 31),
                            IsActive = true,
                            Name = "2026-2027",
                            StartDate = new DateOnly(2026, 6, 1)
                        },
                        new
                        {
                            Id = 2,
                            CampusId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            EndDate = new DateOnly(2027, 3, 31),
                            IsActive = true,
                            Name = "2026-2027",
                            StartDate = new DateOnly(2026, 6, 1)
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.AdmissionApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("AppliedOn")
                        .HasColumnType("date");

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GuardianId")
                        .HasColumnType("int");

                    b.Property<decimal>("RegistrationFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StudentFirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("StudentLastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique();

                    b.HasIndex("CampusId");

                    b.HasIndex("GuardianId");

                    b.HasIndex("SchoolClassId");

                    b.HasIndex("SectionId");

                    b.ToTable("AdmissionApplications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicYearId = 1,
                            ApplicationNumber = "ADM-2026-001",
                            AppliedOn = new DateOnly(2026, 3, 25),
                            CampusId = 1,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateOnly(2020, 8, 12),
                            Gender = "Male",
                            GuardianId = 1,
                            RegistrationFee = 1500m,
                            SchoolClassId = 1,
                            SectionId = 1,
                            Status = "New",
                            StudentFirstName = "Aarav",
                            StudentLastName = "Sharma"
                        },
                        new
                        {
                            Id = 2,
                            AcademicYearId = 1,
                            ApplicationNumber = "ADM-2026-002",
                            AppliedOn = new DateOnly(2026, 3, 22),
                            CampusId = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateOnly(2020, 11, 3),
                            Gender = "Female",
                            GuardianId = 2,
                            RegistrationFee = 1500m,
                            SchoolClassId = 1,
                            SectionId = 2,
                            Status = "Approved",
                            StudentFirstName = "Ishita",
                            StudentLastName = "Verma"
                        },
                        new
                        {
                            Id = 3,
                            AcademicYearId = 2,
                            ApplicationNumber = "ADM-2026-003",
                            AppliedOn = new DateOnly(2026, 3, 27),
                            CampusId = 2,
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateOnly(2020, 4, 19),
                            Gender = "Female",
                            GuardianId = 3,
                            RegistrationFee = 1500m,
                            SchoolClassId = 3,
                            SectionId = 4,
                            Status = "Waitlisted",
                            StudentFirstName = "Diya",
                            StudentLastName = "Nair"
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MarkedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("AttendanceRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceDate = new DateOnly(2026, 4, 1),
                            CreatedAt = new DateTime(2026, 4, 1, 8, 5, 0, 0, DateTimeKind.Local),
                            MarkedOn = new DateTime(2026, 4, 1, 8, 5, 0, 0, DateTimeKind.Local),
                            Status = "Present",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            AttendanceDate = new DateOnly(2026, 4, 2),
                            CreatedAt = new DateTime(2026, 4, 2, 8, 20, 0, 0, DateTimeKind.Local),
                            MarkedOn = new DateTime(2026, 4, 2, 8, 20, 0, 0, DateTimeKind.Local),
                            Remarks = "Arrived after assembly",
                            Status = "Late",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            AttendanceDate = new DateOnly(2026, 4, 3),
                            CreatedAt = new DateTime(2026, 4, 3, 8, 30, 0, 0, DateTimeKind.Local),
                            MarkedOn = new DateTime(2026, 4, 3, 8, 30, 0, 0, DateTimeKind.Local),
                            Remarks = "Parent informed class teacher",
                            Status = "Absent",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardAffiliation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Campuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardAffiliation = "CBSE",
                            City = "Bengaluru",
                            Code = "HQ",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Greenfield Public School",
                            State = "Karnataka"
                        },
                        new
                        {
                            Id = 2,
                            BoardAffiliation = "ICSE",
                            City = "Mysuru",
                            Code = "WEST",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Greenfield West Campus",
                            State = "Karnataka"
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.ExamSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date");

                    b.Property<int>("ExamTermId")
                        .HasColumnType("int");

                    b.Property<int>("MaxMarks")
                        .HasColumnType("int");

                    b.Property<int>("PassMarks")
                        .HasColumnType("int");

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolClassId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("ExamTermId", "SchoolClassId", "SectionId", "SubjectId")
                        .IsUnique();

                    b.ToTable("ExamSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 12, 15, 0, 0, DateTimeKind.Local),
                            DurationMinutes = 90,
                            ExamDate = new DateOnly(2026, 9, 14),
                            ExamTermId = 1,
                            MaxMarks = 100,
                            PassMarks = 35,
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(9, 0, 0),
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 4, 12, 15, 0, 0, DateTimeKind.Local),
                            DurationMinutes = 90,
                            ExamDate = new DateOnly(2026, 9, 15),
                            ExamTermId = 1,
                            MaxMarks = 100,
                            PassMarks = 35,
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(9, 0, 0),
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 4, 12, 15, 0, 0, DateTimeKind.Local),
                            DurationMinutes = 90,
                            ExamDate = new DateOnly(2026, 9, 16),
                            ExamTermId = 1,
                            MaxMarks = 100,
                            PassMarks = 35,
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(9, 0, 0),
                            SubjectId = 3
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.ExamTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("CampusId");

                    b.ToTable("ExamTerms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicYearId = 1,
                            CampusId = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 12, 0, 0, 0, DateTimeKind.Local),
                            EndDate = new DateOnly(2026, 9, 18),
                            ExamType = "Scholastic",
                            Name = "Term 1 Assessment",
                            StartDate = new DateOnly(2026, 9, 14),
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.FeeConcession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateOnly>("ApprovedOn")
                        .HasColumnType("date");

                    b.Property<string>("ConcessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StudentFeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentFeeId");

                    b.ToTable("FeeConcessions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 6000m,
                            ApprovedBy = "Bursar",
                            ApprovedOn = new DateOnly(2026, 4, 4),
                            ConcessionType = "Sibling Concession",
                            CreatedAt = new DateTime(2026, 4, 4, 10, 0, 0, 0, DateTimeKind.Local),
                            Remarks = "Approved for sibling admission",
                            StudentFeeId = 1
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.FeePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentFeeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaymentReference")
                        .IsUnique();

                    b.HasIndex("StudentFeeId");

                    b.HasIndex("StudentId");

                    b.ToTable("FeePayments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 24000m,
                            CreatedAt = new DateTime(2026, 4, 3, 11, 0, 0, 0, DateTimeKind.Local),
                            PaidOn = new DateOnly(2026, 4, 3),
                            PaymentMethod = "UPI",
                            PaymentReference = "RCPT-2026-001",
                            Status = "Posted",
                            StudentFeeId = 1,
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.FeeStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("SchoolClassId");

                    b.HasIndex("CampusId", "AcademicYearId", "SchoolClassId", "FeeCode")
                        .IsUnique();

                    b.ToTable("FeeStructures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicYearId = 1,
                            Amount = 48000m,
                            BillingCycle = "Quarterly",
                            CampusId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Local),
                            FeeCode = "TUITION",
                            FeeName = "Tuition Fee",
                            SchoolClassId = 1
                        },
                        new
                        {
                            Id = 2,
                            AcademicYearId = 1,
                            Amount = 12000m,
                            BillingCycle = "Quarterly",
                            CampusId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 15, 0, 0, DateTimeKind.Local),
                            FeeCode = "TRANSPORT",
                            FeeName = "Transport Fee",
                            SchoolClassId = 1
                        },
                        new
                        {
                            Id = 3,
                            AcademicYearId = 2,
                            Amount = 42000m,
                            BillingCycle = "Quarterly",
                            CampusId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 8, 30, 0, 0, DateTimeKind.Local),
                            FeeCode = "TUITION",
                            FeeName = "Tuition Fee",
                            SchoolClassId = 3
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Guardian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("Email");

                    b.ToTable("Guardians", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampusId = 1,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "ananya.sharma@example.com",
                            FullName = "Ananya Sharma",
                            Occupation = "Architect",
                            PhoneNumber = "9876500001",
                            Relationship = "Mother"
                        },
                        new
                        {
                            Id = 2,
                            CampusId = 1,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "rahul.verma@example.com",
                            FullName = "Rahul Verma",
                            Occupation = "Business Owner",
                            PhoneNumber = "9876500002",
                            Relationship = "Father"
                        },
                        new
                        {
                            Id = 3,
                            CampusId = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "meera.nair@example.com",
                            FullName = "Meera Nair",
                            Occupation = "Doctor",
                            PhoneNumber = "9876500003",
                            Relationship = "Mother"
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampusId", "Code")
                        .IsUnique();

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampusId = 1,
                            Code = "GRADE-1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 1,
                            Name = "Grade 1"
                        },
                        new
                        {
                            Id = 2,
                            CampusId = 1,
                            Code = "GRADE-2",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 2,
                            Name = "Grade 2"
                        },
                        new
                        {
                            Id = 3,
                            CampusId = 2,
                            Code = "GRADE-1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DisplayOrder = 1,
                            Name = "Grade 1"
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.SchoolHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("HolidayDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampusId", "HolidayDate", "Title")
                        .IsUnique();

                    b.ToTable("SchoolHolidays", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampusId = 1,
                            Category = "National Holiday",
                            CreatedAt = new DateTime(2026, 4, 5, 9, 0, 0, 0, DateTimeKind.Local),
                            HolidayDate = new DateOnly(2026, 4, 14),
                            Title = "Ambedkar Jayanti"
                        },
                        new
                        {
                            Id = 2,
                            CampusId = 1,
                            Category = "School Event",
                            CreatedAt = new DateTime(2026, 4, 5, 9, 10, 0, 0, DateTimeKind.Local),
                            HolidayDate = new DateOnly(2026, 4, 18),
                            Title = "PTM Preparation Day"
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolClassId", "Name")
                        .IsUnique();

                    b.ToTable("Sections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "A",
                            RoomNumber = "G1-A01",
                            SchoolClassId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "B",
                            RoomNumber = "G1-B01",
                            SchoolClassId = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "A",
                            RoomNumber = "G2-A01",
                            SchoolClassId = 2
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "A",
                            RoomNumber = "W-G1-A01",
                            SchoolClassId = 3
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("AdmissionApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("AdmissionNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EnrolledOn")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GuardianId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimaryContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("AdmissionApplicationId");

                    b.HasIndex("AdmissionNumber")
                        .IsUnique();

                    b.HasIndex("CampusId");

                    b.HasIndex("GuardianId");

                    b.HasIndex("SchoolClassId");

                    b.HasIndex("SectionId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicYearId = 1,
                            AddressLine = "45 Green Residency, Maple Street",
                            AdmissionApplicationId = 2,
                            AdmissionNumber = "STU-2026-001",
                            BloodGroup = "B+",
                            CampusId = 1,
                            City = "Bengaluru",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateOnly(2020, 11, 3),
                            EnrolledOn = new DateOnly(2026, 4, 1),
                            FirstName = "Ishita",
                            Gender = "Female",
                            GuardianId = 2,
                            LastName = "Verma",
                            MedicalNotes = "Dust allergy",
                            PostalCode = "560001",
                            PrimaryContactNumber = "9876500002",
                            SchoolClassId = 1,
                            SectionId = 2,
                            State = "Karnataka",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.StudentDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SubmittedOn")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("VerifiedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentDocuments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Local),
                            DocumentType = "Birth Certificate",
                            Remarks = "Original verified at front desk",
                            Status = "Verified",
                            StudentId = 1,
                            SubmittedOn = new DateOnly(2026, 4, 1),
                            VerifiedOn = new DateOnly(2026, 4, 1)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 9, 30, 0, 0, DateTimeKind.Local),
                            DocumentType = "Transfer Certificate",
                            Remarks = "Awaiting previous school submission",
                            Status = "Pending",
                            StudentId = 1,
                            SubmittedOn = new DateOnly(2026, 4, 1)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 2, 10, 15, 0, 0, DateTimeKind.Local),
                            DocumentType = "Immunization Record",
                            Remarks = "Uploaded by guardian and reviewed",
                            Status = "Verified",
                            StudentId = 1,
                            SubmittedOn = new DateOnly(2026, 4, 2),
                            VerifiedOn = new DateOnly(2026, 4, 2)
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.StudentExamScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("MarksObtained")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ExamScheduleId", "StudentId")
                        .IsUnique();

                    b.ToTable("StudentExamScores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 12, 30, 0, 0, DateTimeKind.Local),
                            ExamScheduleId = 1,
                            Grade = "A",
                            MarksObtained = 86m,
                            Remarks = "Strong comprehension",
                            ResultStatus = "Pass",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 4, 12, 30, 0, 0, DateTimeKind.Local),
                            ExamScheduleId = 2,
                            Grade = "A+",
                            MarksObtained = 91m,
                            Remarks = "Excellent problem solving",
                            ResultStatus = "Pass",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 4, 12, 30, 0, 0, DateTimeKind.Local),
                            ExamScheduleId = 3,
                            Grade = "B+",
                            MarksObtained = 78m,
                            Remarks = "Good scientific reasoning",
                            ResultStatus = "Pass",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.StudentFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date");

                    b.Property<int>("FeeStructureId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FeeStructureId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentFees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 48000m,
                            AmountPaid = 24000m,
                            CreatedAt = new DateTime(2026, 4, 2, 9, 0, 0, 0, DateTimeKind.Local),
                            DueOn = new DateOnly(2026, 6, 10),
                            FeeStructureId = 1,
                            Status = "Partially Paid",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 12000m,
                            AmountPaid = 0m,
                            CreatedAt = new DateTime(2026, 4, 2, 9, 10, 0, 0, DateTimeKind.Local),
                            DueOn = new DateOnly(2026, 6, 10),
                            FeeStructureId = 2,
                            Status = "Pending",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.StudentLeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("LeaveDate")
                        .HasColumnType("date");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "LeaveDate")
                        .IsUnique();

                    b.ToTable("StudentLeaveRequests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 3, 7, 30, 0, 0, DateTimeKind.Local),
                            LeaveDate = new DateOnly(2026, 4, 3),
                            LeaveType = "Sick Leave",
                            Reason = "Fever and rest advised",
                            Status = "Approved",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeeklyPeriods")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampusId", "Code")
                        .IsUnique();

                    b.ToTable("Subjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampusId = 1,
                            Category = "Language",
                            Code = "ENG",
                            CreatedAt = new DateTime(2026, 4, 4, 8, 0, 0, 0, DateTimeKind.Local),
                            Name = "English",
                            WeeklyPeriods = 6
                        },
                        new
                        {
                            Id = 2,
                            CampusId = 1,
                            Category = "Core",
                            Code = "MAT",
                            CreatedAt = new DateTime(2026, 4, 4, 8, 0, 0, 0, DateTimeKind.Local),
                            Name = "Mathematics",
                            WeeklyPeriods = 7
                        },
                        new
                        {
                            Id = 3,
                            CampusId = 1,
                            Category = "Core",
                            Code = "SCI",
                            CreatedAt = new DateTime(2026, 4, 4, 8, 0, 0, 0, DateTimeKind.Local),
                            Name = "Science",
                            WeeklyPeriods = 5
                        },
                        new
                        {
                            Id = 4,
                            CampusId = 1,
                            Category = "Humanities",
                            Code = "SST",
                            CreatedAt = new DateTime(2026, 4, 4, 8, 0, 0, 0, DateTimeKind.Local),
                            Name = "Social Studies",
                            WeeklyPeriods = 4
                        },
                        new
                        {
                            Id = 5,
                            CampusId = 1,
                            Category = "Activity",
                            Code = "ART",
                            CreatedAt = new DateTime(2026, 4, 4, 8, 0, 0, 0, DateTimeKind.Local),
                            Name = "Art & Craft",
                            WeeklyPeriods = 2
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.TimetablePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SchoolClassId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolClassId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("AcademicYearId", "SchoolClassId", "SectionId", "DayOfWeek", "PeriodNumber")
                        .IsUnique();

                    b.ToTable("TimetablePeriods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicYearId = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 8, 15, 0, 0, DateTimeKind.Local),
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(9, 10, 0),
                            PeriodNumber = 1,
                            RoomNumber = "G1-B01",
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(8, 30, 0),
                            SubjectId = 1,
                            TeacherName = "Anita Rao"
                        },
                        new
                        {
                            Id = 2,
                            AcademicYearId = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 8, 15, 0, 0, DateTimeKind.Local),
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(9, 50, 0),
                            PeriodNumber = 2,
                            RoomNumber = "G1-B01",
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(9, 10, 0),
                            SubjectId = 2,
                            TeacherName = "Rahul Mehta"
                        },
                        new
                        {
                            Id = 3,
                            AcademicYearId = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 8, 15, 0, 0, DateTimeKind.Local),
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(10, 45, 0),
                            PeriodNumber = 3,
                            RoomNumber = "SCIENCE LAB",
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(10, 5, 0),
                            SubjectId = 3,
                            TeacherName = "Priya Nair"
                        },
                        new
                        {
                            Id = 4,
                            AcademicYearId = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 8, 15, 0, 0, DateTimeKind.Local),
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(9, 10, 0),
                            PeriodNumber = 1,
                            RoomNumber = "G1-B01",
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(8, 30, 0),
                            SubjectId = 2,
                            TeacherName = "Rahul Mehta"
                        },
                        new
                        {
                            Id = 5,
                            AcademicYearId = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 8, 15, 0, 0, DateTimeKind.Local),
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(9, 50, 0),
                            PeriodNumber = 2,
                            RoomNumber = "G1-B01",
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(9, 10, 0),
                            SubjectId = 1,
                            TeacherName = "Anita Rao"
                        },
                        new
                        {
                            Id = 6,
                            AcademicYearId = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 8, 15, 0, 0, DateTimeKind.Local),
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(10, 45, 0),
                            PeriodNumber = 3,
                            RoomNumber = "G1-B01",
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(10, 5, 0),
                            SubjectId = 4,
                            TeacherName = "Kavya Iyer"
                        },
                        new
                        {
                            Id = 7,
                            AcademicYearId = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 8, 15, 0, 0, DateTimeKind.Local),
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(9, 10, 0),
                            PeriodNumber = 1,
                            RoomNumber = "SCIENCE LAB",
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(8, 30, 0),
                            SubjectId = 3,
                            TeacherName = "Priya Nair"
                        },
                        new
                        {
                            Id = 8,
                            AcademicYearId = 1,
                            CreatedAt = new DateTime(2026, 4, 4, 8, 15, 0, 0, DateTimeKind.Local),
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(9, 50, 0),
                            PeriodNumber = 2,
                            RoomNumber = "ART ROOM",
                            SchoolClassId = 1,
                            SectionId = 2,
                            StartTime = new TimeOnly(9, 10, 0),
                            SubjectId = 5,
                            TeacherName = "Neha Kapoor"
                        });
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.AcademicYear", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.Campus", "Campus")
                        .WithMany("AcademicYears")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.AdmissionApplication", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.AcademicYear", "AcademicYear")
                        .WithMany("AdmissionApplications")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Campus", "Campus")
                        .WithMany("AdmissionApplications")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Guardian", "Guardian")
                        .WithMany("AdmissionApplications")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.SchoolClass", "SchoolClass")
                        .WithMany("AdmissionApplications")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Section", "Section")
                        .WithMany("AdmissionApplications")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Campus");

                    b.Navigation("Guardian");

                    b.Navigation("SchoolClass");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.Student", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.ExamSchedule", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.ExamTerm", "ExamTerm")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("ExamTermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.SchoolClass", "SchoolClass")
                        .WithMany()
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Subject", "Subject")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamTerm");

                    b.Navigation("SchoolClass");

                    b.Navigation("Section");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.ExamTerm", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.FeeConcession", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.StudentFee", "StudentFee")
                        .WithMany("Concessions")
                        .HasForeignKey("StudentFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentFee");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.FeePayment", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.StudentFee", "StudentFee")
                        .WithMany("Payments")
                        .HasForeignKey("StudentFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Student", "Student")
                        .WithMany("FeePayments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentFee");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.FeeStructure", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.AcademicYear", "AcademicYear")
                        .WithMany("FeeStructures")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Campus", "Campus")
                        .WithMany("FeeStructures")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.SchoolClass", "SchoolClass")
                        .WithMany("FeeStructures")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Campus");

                    b.Navigation("SchoolClass");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Guardian", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.Campus", "Campus")
                        .WithMany("Guardians")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.SchoolClass", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.Campus", "Campus")
                        .WithMany("Classes")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.SchoolHoliday", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.Campus", "Campus")
                        .WithMany("Holidays")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Section", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.SchoolClass", "SchoolClass")
                        .WithMany("Sections")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchoolClass");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Student", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.AcademicYear", "AcademicYear")
                        .WithMany("Students")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.AdmissionApplication", "AdmissionApplication")
                        .WithMany("Students")
                        .HasForeignKey("AdmissionApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Campus", "Campus")
                        .WithMany("Students")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Guardian", "Guardian")
                        .WithMany("Students")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.SchoolClass", "SchoolClass")
                        .WithMany("Students")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Section", "Section")
                        .WithMany("Students")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("AdmissionApplication");

                    b.Navigation("Campus");

                    b.Navigation("Guardian");

                    b.Navigation("SchoolClass");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.StudentDocument", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.Student", "Student")
                        .WithMany("Documents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.StudentExamScore", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.ExamSchedule", "ExamSchedule")
                        .WithMany("StudentExamScores")
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSchedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.StudentFee", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.FeeStructure", "FeeStructure")
                        .WithMany("StudentFees")
                        .HasForeignKey("FeeStructureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Student", "Student")
                        .WithMany("Fees")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeStructure");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.StudentLeaveRequest", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.Student", "Student")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Subject", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.TimetablePeriod", b =>
                {
                    b.HasOne("EducationERP.Domain.Entities.AcademicYear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.SchoolClass", "SchoolClass")
                        .WithMany()
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationERP.Domain.Entities.Subject", "Subject")
                        .WithMany("TimetablePeriods")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("SchoolClass");

                    b.Navigation("Section");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.AcademicYear", b =>
                {
                    b.Navigation("AdmissionApplications");

                    b.Navigation("FeeStructures");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.AdmissionApplication", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Campus", b =>
                {
                    b.Navigation("AcademicYears");

                    b.Navigation("AdmissionApplications");

                    b.Navigation("Classes");

                    b.Navigation("FeeStructures");

                    b.Navigation("Guardians");

                    b.Navigation("Holidays");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.ExamSchedule", b =>
                {
                    b.Navigation("StudentExamScores");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.ExamTerm", b =>
                {
                    b.Navigation("ExamSchedules");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.FeeStructure", b =>
                {
                    b.Navigation("StudentFees");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Guardian", b =>
                {
                    b.Navigation("AdmissionApplications");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.SchoolClass", b =>
                {
                    b.Navigation("AdmissionApplications");

                    b.Navigation("FeeStructures");

                    b.Navigation("Sections");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Section", b =>
                {
                    b.Navigation("AdmissionApplications");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Student", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Documents");

                    b.Navigation("FeePayments");

                    b.Navigation("Fees");

                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.StudentFee", b =>
                {
                    b.Navigation("Concessions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EducationERP.Domain.Entities.Subject", b =>
                {
                    b.Navigation("ExamSchedules");

                    b.Navigation("TimetablePeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
